using DevExpress.XtraPivotGrid;
using System;
using System.IO;
using System.Windows.Forms;

namespace WinPivotUpgradeLayout
{
    public partial class Form1 : Form{
        MemoryStream layoutStream = new MemoryStream();
        public Form1(){
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            pivotGridControlNew.OptionsLayout.Columns.AddNewColumns = true;
            pivotGridControlNew.OptionsLayout.Columns.RemoveOldColumns = false;
            pivotGridControlNew.OptionsLayout.AddNewGroups = true;
            pivotGridControlOld.OptionsLayout.LayoutVersion = "1.0";
            pivotGridControlNew.OptionsLayout.LayoutVersion = "2.0";

        }
        private void Form1_Load(object sender, EventArgs e){
            PivotGridField fieldProductName = pivotGridControlOld.Fields["fieldProductName"];
            pivotGridControlOld.BeginUpdate();
            try{
                fieldProductName.FilterValues.Clear();
                fieldProductName.FilterValues.Add("Chai");
                fieldProductName.FilterValues.Add("Chang");
                fieldProductName.FilterValues.Add("Chartreuse verte");
                fieldProductName.FilterValues.Add("Aniseed Syrup");
                fieldProductName.FilterValues.Add("Genen Shouyu");
                fieldProductName.FilterValues.Add("Gula Malacca");
                fieldProductName.FilterValues.FilterType = DevExpress.XtraPivotGrid.PivotFilterType.Included;

            }
            finally{
                pivotGridControlOld.EndUpdate();
            }
        }
        private void simpleButton1_Click(object sender, EventArgs e){
            pivotGridControlOld.SaveLayoutToStream(layoutStream);
        }
        private void simpleButton2_Click(object sender, EventArgs e){
            if (layoutStream.Length > 0) {
                layoutStream.Seek(0, SeekOrigin.Begin);
                pivotGridControlNew.RestoreLayoutFromStream(layoutStream);
            }
            pivotGridControlNew.CollapseAll();

        }
        private void pivotGridControlNew_LayoutUpgrade(object sender, DevExpress.Utils.LayoutUpgradeEventArgs e){
            if (e.PreviousVersion == "1.0"){
                var newField = new PivotGridField(){
                    FieldName = "Quantity",
                    Caption = "Quantity",
                    Name = "fieldQuantity",
                    Area = DevExpress.XtraPivotGrid.PivotArea.DataArea
                };
                pivotGridControlNew.Fields.Add(newField);
            };
        }
    }
}
